### PR TITLE
Update React dependency to 0.14.0

### PR DESCRIPTION
**Pull request by ghost**
Might save you two or three minutes...

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks for the patch! However, your patch contains a few things unrelated to the pull request that need to be removed before I can merge. The changes to the Brutha version number need to be cut out, and the ClojureScript dependency update should be in a separate commit, and ideally a separate PR.

**Comment by ghost** [comment]
Can do.

**Comment by ghost** [comment]
OK, disentangled.  ClojureScript updates are waiting in the wings for a separate pull request.

**Comment by weavejester** [comment]
Thanks!

You've changed it to use the `ReactDOM` object, but there are parts of the code that still use the `React` object. Do those pieces still work?

**Comment by ghost** [comment]
Ack, you're right!  I missed one.  Didn't test unmount.  Anyway, yes createClass and createFactory are unmoved.  (See https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#two-packages-react-and-react-dom fourth paragraph down)  And React is loaded as a transitive dependency by the cljsjs/react-dom package, so everything is still there.

**Comment by weavejester** [comment]
Okay, thanks! Let me check it over myself and then I'll merge.

**Pull request merged**
